spring.application.name=cv



# Database config
spring.datasource.url=jdbc:postgresql://ep-floral-cherry-a4otv40c-pooler.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_5lhGQFEdHNb9

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true  
spring.jpa.properties.hibernate.format_sql=true


# JWT config (we'll use these later)
jwt.secret=your_super_secret_key_here  
jwt.expiration=86400000

spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY:dummy-key}
spring.ai.openai.api-key=${OPENAI_API_KEY:dummy-key}